export type ProjectCapability =
    | "IDENTIFIER_OCCUPANCY"
    | "IDENTIFIER_OCCURRENCES"
    | "LOOP_HOIST_NAME_RESOLUTION"
    | "RENAME_CONFLICT_PLANNING";

export type UnsafeReasonCode =
    | "MISSING_PROJECT_CONTEXT"
    | "NAME_COLLISION"
    | "CROSS_FILE_CONFLICT"
    | "SEMANTIC_AMBIGUITY"
    | "NON_IDEMPOTENT_EXPRESSION";
