export type * from "./ast.js";
export { emitBuiltinFunction, isBuiltinFunction } from "./builtins.js";
export { wrapConditional, wrapConditionalBody, wrapRawBody } from "./code-wrapping.js";
export { tryFoldConstantExpression } from "./constant-folding.js";
export { GmlToJsEmitter } from "./emitter.js";
export { emitJavaScript } from "./emitter-entrypoints.js";
export { lowerEnumDeclaration } from "./enum-lowering.js";
export { EventContextOracle } from "./event-context-oracle.js";
export { normalizeGmlNumericLiteral } from "./literal-normalization.js";
export { collectLocalVariables } from "./local-variable-collector.js";
export { mapBinaryOperator, mapUnaryOperator } from "./operator-mapping.js";
export type { SemanticOracleOptions } from "./semantic-factory.js";
export { createSemanticOracle } from "./semantic-factory.js";
export { StringBuilder } from "./string-builder.js";
export { lowerWithStatement } from "./with-lowering.js";
