/**
 * GML literal normalization for the transpiler emitter.
 *
 * GML supports numeric literal syntaxes that are not valid JavaScript:
 *   - Dollar-sign hex prefix: `$FF` (GML) → `0xFF` (JS)
 *   - Hash hex prefix: `#FFFFFF` (GML) → `0xFFFFFF` (JS)
 *
 * Standard-format literals are preserved as-is because JavaScript already
 * understands them:
 *   - `0xFF` (0x-prefixed hex) → `0xFF` (unchanged)
 *   - `0b1010` (binary) → `0b1010` (unchanged)
 *   - All other literals → unchanged
 *
 * This normalization is necessary for the hot-reload pipeline: patches
 * generated by the transpiler must be runnable as JavaScript in the
 * GameMaker HTML5 runtime without syntax errors.
 */

/**
 * Pattern matching a GML hash-prefixed hex literal (`#FF`, `#FFFFFF`, etc.).
 * The hash prefix is only treated as hex when it is followed exclusively by
 * hexadecimal digits (no spaces, colons, or other CSS-style extensions).
 */
const HASH_HEX_PATTERN = /^#[0-9A-Fa-f]+$/;

/**
 * Normalize a GML numeric literal string to a valid JavaScript literal.
 *
 * Converts GML-specific hex prefixes to the standard `0x` prefix understood
 * by JavaScript:
 *   - `$FF`     → `0xFF`
 *   - `#FFFFFF` → `0xFFFFFF`
 *   - `0xFF`    → `0xFF`    (already valid, no change)
 *   - `0b1010`  → `0b1010`  (already valid, no change)
 *   - `255`     → `255`     (decimal, no change)
 *
 * @param value - The raw literal string from the GML AST
 * @returns The normalized literal string safe for JavaScript emission
 */
export function normalizeGmlNumericLiteral(value: string): string {
    // GML dollar-sign hex prefix: $FF → 0xFF
    if (value.startsWith("$")) {
        return `0x${value.slice(1)}`;
    }
    // GML hash hex prefix: #FFFFFF → 0xFFFFFF
    // Guard with a pattern check to avoid mishandling non-hex hash strings.
    if (HASH_HEX_PATTERN.test(value)) {
        return `0x${value.slice(1)}`;
    }
    return value;
}
