import * as Modules from "./src/index.js";

export const RuntimeWrapper = Object.freeze({
    ...Modules.Runtime,
    ...Modules.Clients
});

export type {
    ApplyPatchResult,
    ErrorAnalytics,
    GeneralLogger,
    Logger,
    LoggerConfiguration,
    LoggerOptions,
    LogLevel,
    MessageEventLike,
    Patch,
    PatchErrorAnalytics,
    PatchErrorCategory,
    PatchErrorOccurrence,
    PatchErrorSummary,
    PatchHistoryEntry,
    PatchKind,
    PatchLifecycleLogger,
    PatchQueueMetrics,
    PatchQueueOptions,
    PatchQueueState,
    PatchStats,
    RegistryLifecycleLogger,
    RuntimeFunction,
    RuntimePatchError,
    RuntimeRegistry,
    RuntimeRegistryOverrides,
    RuntimeRegistrySnapshot,
    RuntimeWebSocketClient,
    RuntimeWebSocketConstructor,
    RuntimeWebSocketInstance,
    RuntimeWrapper as RuntimeWrapperApi,
    RuntimeWrapperOptions,
    RuntimeWrapperState,
    TrySafeApplyResult,
    WebSocketClientOptions,
    WebSocketClientState,
    WebSocketConnectionLifecycle,
    WebSocketConnectionMetrics,
    WebSocketEvent,
    WebSocketInstanceProvider,
    WebSocketLogger,
    WebSocketMessageSender,
    WebSocketMetricsCollector,
    WebSocketPatchQueueManager
} from "./src/index.js";
