export {
    applyEnvironmentOverride,
    asArray,
    assertArray,
    assertFunction,
    assertNonEmptyString,
    assertPlainObject,
    coerceNonNegativeInteger,
    coercePositiveInteger,
    collectAncestorDirectories,
    collectUniqueAncestorDirectories,
    createAbortGuard,
    createEnvConfiguredValue,
    createEnvConfiguredValueWithFallback,
    createListSplitPattern,
    escapeRegExp,
    ensureMap,
    getErrorCode,
    getErrorMessage,
    getErrorMessageOrFallback,
    getIdentifierText,
    getNonEmptyTrimmedString,
    getOrCreateMapEntry,
    hasOwn,
    identity,
    incrementMapValue,
    isAggregateErrorLike,
    isErrorLike,
    isErrorWithCode,
    isFiniteNumber,
    isFsErrorCode,
    isJsonParseError,
    isMissingModuleDependency,
    isNonEmptyArray,
    isNonEmptyString,
    isNonEmptyTrimmedString,
    isObjectLike,
    isPathInside,
    JsonParseError,
    noop,
    normalizeEnumeratedOption,
    normalizeIdentifierMetadataEntries,
    normalizeStringList,
    parseJsonObjectWithContext,
    parseJsonWithContext,
    resolveContainedRelativePath,
    resolveFunction,
    resolveIntegerOption,
    resolveModuleDefaultExport,
    splitLines,
    stringifyJsonForFile,
    toArray,
    toMutableArray,
    toNormalizedInteger,
    toNormalizedLowerCaseSet,
    toNormalizedLowerCaseString,
    toPosixPath,
    toTrimmedString,
    uniqueArray
} from "../dependencies.js";

export { resolveCommandUsage } from "../core/command-usage.js";

export { appendToCollection } from "../core/collection-utils.js";

export { ensureDir } from "./ensure-dir.js";

export {
    createCliRunSkippedError,
    isCliRunSkipped,
    SKIP_CLI_RUN_ENV_VAR
} from "./skip-cli-run.js";
