// AST helpers are now provided by @gml-modules/core
// TODO: Remove this import-export shim; migrate callers to import directly/properly
import { Core } from "@gml-modules/core";

const {
    AST: {
        cloneAstNode,
        getSingleVariableDeclarator,
        getVariableDeclarationKind,
        getIdentifierText,
        getCallExpressionArguments,
        getCallExpressionIdentifier,
        getCallExpressionIdentifierName,
        isCallExpressionIdentifierMatch,
        forEachNodeChild,
        getArrayProperty,
        hasArrayPropertyEntries,
        getBodyStatements,
        hasBodyStatements,
        isProgramOrBlockStatement,
        getSingleMemberIndexPropertyEntry,
        getBooleanLiteralValue,
        isBooleanLiteral,
        isUndefinedLiteral,
        isUndefinedSentinel,
        getNodeType,
        isNode,
        isFunctionLikeNode,
        visitChildNodes,
        enqueueObjectChildValues,
        unwrapParenthesizedExpression,
        isVariableDeclarationOfKind,
        isVarVariableDeclaration,
        createIdentifierNode,
        isBinaryOperator,
        getStructPropertyAccess
    }
} = Core;
export {
    cloneAstNode,
    getSingleVariableDeclarator,
    getVariableDeclarationKind,
    getIdentifierText,
    getCallExpressionArguments,
    getCallExpressionIdentifier,
    getCallExpressionIdentifierName,
    isCallExpressionIdentifierMatch,
    forEachNodeChild,
    getArrayProperty,
    hasArrayPropertyEntries,
    getBodyStatements,
    hasBodyStatements,
    isProgramOrBlockStatement,
    getSingleMemberIndexPropertyEntry,
    getBooleanLiteralValue,
    isBooleanLiteral,
    isUndefinedLiteral,
    isUndefinedSentinel,
    getNodeType,
    isNode,
    isFunctionLikeNode,
    visitChildNodes,
    enqueueObjectChildValues,
    unwrapParenthesizedExpression,
    isVariableDeclarationOfKind,
    isVarVariableDeclaration,
    createIdentifierNode,
    isBinaryOperator,
    getStructPropertyAccess
};
