export {
    appendToCollection,
    applyEnvironmentOverride,
    asArray,
    assertArray,
    assertFunction,
    assertFunctionProperties,
    assertNonEmptyString,
    assertPlainObject,
    coerceNonNegativeInteger,
    coercePositiveInteger,
    compactArray,
    createAbortGuard,
    createEnvConfiguredValue,
    createEnvConfiguredValueWithFallback,
    createListSplitPattern,
    createNumericTypeErrorFormatter,
    describeValueForError,
    describeValueWithArticle,
    ensureMap,
    escapeRegExp,
    getErrorCode,
    getErrorMessage,
    getErrorMessageOrFallback,
    getIdentifierText,
    getNonEmptyTrimmedString,
    getOrCreateMapEntry,
    getObjectTagName,
    hasOwn,
    callWithFallback,
    identity,
    incrementMapValue,
    isAggregateErrorLike,
    isErrorLike,
    isErrorWithCode,
    isFiniteNumber,
    isFsErrorCode,
    isJsonParseError,
    isNonEmptyArray,
    isNonEmptyString,
    isNonEmptyTrimmedString,
    isObjectLike,
    isObjectOrFunction,
    isPathInside,
    JsonParseError,
    mergeUniqueValues,
    noop,
    normalizeEnumeratedOption,
    normalizeExtensionSuffix,
    normalizeIdentifierMetadataEntries,
    normalizeStringList,
    parseJsonObjectWithContext,
    parseJsonWithContext,
    pushUnique,
    resolveContainedRelativePath,
    resolveEnvironmentMap,
    resolveIntegerOption,
    splitLines,
    stringifyJsonForFile,
    formatWithIndefiniteArticle,
    toArray,
    toArrayFromIterable,
    toMutableArray,
    toFiniteNumber,
    toNormalizedInteger,
    toNormalizedLowerCaseSet,
    toNormalizedLowerCaseString,
    toPosixPath,
    toTrimmedString,
    uniqueArray,
    walkAncestorDirectories,
    withObjectLike
} from "@prettier-plugin-gml/shared";

export { Command, InvalidArgumentError, Option } from "commander";

export {
    isMissingModuleDependency,
    resolveModuleDefaultExport
} from "./shared/module.js";

export { ensureDir } from "./shared/ensure-dir.js";

export {
    createVerboseDurationLogger,
    formatDuration,
    timeSync
} from "./shared/reporting/time.js";

export { createEnumeratedOptionHelpers } from "./shared/enumerated-option-helpers.js";
