import { Core } from "@gml-modules/core";

const {
    Utils: {
        appendToCollection,
        applyEnvironmentOverride,
        asArray,
        assertArray,
        assertFunction,
        assertFunctionProperties,
        assertNonEmptyString,
        assertPlainObject,
        coerceNonNegativeInteger,
        coercePositiveInteger,
        compactArray,
        createAbortGuard,
        createEnvConfiguredValue,
        createEnvConfiguredValueWithFallback,
        createListSplitPattern,
        createNumericTypeErrorFormatter,
        describeValueForError,
        describeValueWithArticle,
        ensureMap,
        escapeRegExp,
        getErrorCode,
        getErrorMessage,
        getErrorMessageOrFallback,
        getNonEmptyTrimmedString,
        getOrCreateMapEntry,
        getObjectTagName,
        callWithFallback,
        identity,
        incrementMapValue,
        isAggregateErrorLike,
        isErrorLike,
        isErrorWithCode,
        isFiniteNumber,
        isJsonParseError,
        isNonEmptyArray,
        isNonEmptyString,
        isNonEmptyTrimmedString,
        isObjectLike,
        isObjectOrFunction,
        JsonParseError,
        mergeUniqueValues,
        noop,
        normalizeEnumeratedOption,
        normalizeExtensionSuffix,
        normalizeStringList,
        parseJsonObjectWithContext,
        parseJsonWithContext,
        pushUnique,
        resolveEnvironmentMap,
        resolveIntegerOption,
        splitLines,
        stringifyJsonForFile,
        formatWithIndefiniteArticle,
        toArray,
        toArrayFromIterable,
        toMutableArray,
        toFiniteNumber,
        toNormalizedInteger,
        toNormalizedLowerCaseSet,
        toNormalizedLowerCaseString,
        toTrimmedString,
        uniqueArray,
        withObjectLike
    },
    AST: { getIdentifierText },
    FS: {
        isFsErrorCode,
        isPathInside,
        resolveContainedRelativePath,
        toPosixPath,
        walkAncestorDirectories
    },
    IdentifierMetadata: { normalizeIdentifierMetadataEntries }
} = Core;
export {
    appendToCollection,
    applyEnvironmentOverride,
    asArray,
    assertArray,
    assertFunction,
    assertFunctionProperties,
    assertNonEmptyString,
    assertPlainObject,
    coerceNonNegativeInteger,
    coercePositiveInteger,
    compactArray,
    createAbortGuard,
    createEnvConfiguredValue,
    createEnvConfiguredValueWithFallback,
    createListSplitPattern,
    createNumericTypeErrorFormatter,
    describeValueForError,
    describeValueWithArticle,
    ensureMap,
    escapeRegExp,
    getErrorCode,
    getErrorMessage,
    getErrorMessageOrFallback,
    getIdentifierText,
    getNonEmptyTrimmedString,
    getOrCreateMapEntry,
    getObjectTagName,
    callWithFallback,
    identity,
    incrementMapValue,
    isAggregateErrorLike,
    isErrorLike,
    isErrorWithCode,
    isFiniteNumber,
    isFsErrorCode,
    isJsonParseError,
    isNonEmptyArray,
    isNonEmptyString,
    isNonEmptyTrimmedString,
    isObjectLike,
    isObjectOrFunction,
    isPathInside,
    JsonParseError,
    mergeUniqueValues,
    noop,
    normalizeEnumeratedOption,
    normalizeExtensionSuffix,
    normalizeIdentifierMetadataEntries,
    normalizeStringList,
    parseJsonObjectWithContext,
    parseJsonWithContext,
    pushUnique,
    resolveContainedRelativePath,
    resolveEnvironmentMap,
    resolveIntegerOption,
    splitLines,
    stringifyJsonForFile,
    formatWithIndefiniteArticle,
    toArray,
    toArrayFromIterable,
    toMutableArray,
    toFiniteNumber,
    toNormalizedInteger,
    toNormalizedLowerCaseSet,
    toNormalizedLowerCaseString,
    toPosixPath,
    toTrimmedString,
    uniqueArray,
    walkAncestorDirectories,
    withObjectLike
};

export { Command, InvalidArgumentError, Option } from "commander";

export {
    isMissingModuleDependency,
    resolveModuleDefaultExport
} from "./shared/module.js";

export { ensureDir } from "./shared/ensure-dir.js";

export {
    createVerboseDurationLogger,
    formatDuration,
    timeSync
} from "./shared/reporting/time.js";

export { createEnumeratedOptionHelpers } from "./shared/enumerated-option-helpers.js";
