#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"  # optional but recommended
set -eu

if [ -x "$HOME/.githooks/post-commit" ]; then
  echo "Chaining to global post-commit hook"
  chain="${GIT_HOOK_CHAIN:-0}"
  chain=$((chain + 1))
  GIT_HOOK_CHAIN="$chain" "$HOME/.githooks/post-commit" "$@" || true
fi

exit 0