name: Codex 79 – Cohesion Refactor

on:
  schedule:
    - cron: "25 */5 * * *" # every 5 hours at minute 25
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Cohesion Refactor"
      pr_body: |
        Seed PR prompting Codex to consolidate duplicate helpers and boost module cohesion
        without overhauling the entire codebase.
      prompt: >
        Hunt for fragmented helpers or duplicated utilities that should live together.
        Extract or merge them into a shared module with clear ownership so related code
        sits side-by-side. When minting a brand-new helper, strongly prefer situations
        where the function will be called at least three times and contain five or more
        lines of executable logic (excluding comments and blank lines) so the addition
        carries its weight, unless you have a well-supported reason to do otherwise.
        Update imports/exports accordingly and keep changes targeted to one cohesive
        slice of the project.

        Requirements:
          • Accept optional allow/deny path lists from workflow inputs. Honor them to avoid
            touching restricted directories.
          • Provide a migration note in the PR body summarizing renamed symbols, moved files,
            and how downstream extensions should adapt.
          • Run unit tests, lint, and formatting checks and record results in the PR body.
          • Avoid rewriting public APIs unless absolutely necessary; prefer drop-in
            replacements that reduce duplication.

        If no safe consolidation exists, describe the investigation in the PR body and
        propose a follow-up plan instead of submitting a noisy change.
