name: Codex 16 – Dead Code & Asset Audit
on:
  schedule:
    - cron: "10 9 * * *" # 09:10 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Dead Code & Asset Audit"
      pr_body: |
        Automated audit to identify and prune confirmed unused or obsolete code, assets, and documentation.

        **Objective:** Maintain a clean, purposeful repository by safely removing code or assets that are no longer referenced, used, or relevant.
      prompt: >
        Perform a conservative audit of the repository to locate **confirmed unused or legacy items**, such as:
        - Functions, variables, or classes that are never referenced or imported;
        - Files, assets, or documentation sections that are redundant or superseded;
        - Duplicate definitions that can be safely consolidated.

        Only propose removal or consolidation if there is **clear evidence** of obsolescence:
        - Verify that the item is not referenced, imported, or required by any active feature, build script, or configuration;
        - Cross-check recent commits and branches for related changes (e.g., in-flight features or pending integrations);
        - Prefer flagging questionable items with inline comments or TODOs over outright deletion if any uncertainty remains.

        Each change should be:
        - **Tightly scoped** (one well-justified cleanup per PR);
        - **Non-breaking** (no effect on build, tests, or runtime);
        - **Documented** in the commit description, explaining why the removal is safe.

        If nothing meets the removal criteria, provide a note confirming the audit's no-op completion.
