name: Codex 24 – Verbose Loop Cleanup

on:
  schedule:
    # hourly cadence
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Verbose Loop Cleanup"
      pr_body: "Seed PR for Codex to replace hand-rolled loops with tighter constructs."
      prompt: |
        Find a hand-written loop (for/while/forEach-style) that is longer or more
        error-prone than necessary, and swap it for a clearer pattern—such as array
        methods, small helpers, generators, or early exits—that keeps behaviour intact.
        Prioritise loops that duplicate built-in capabilities, mutate shared state in
        multiple places, or include manual index/accumulator bookkeeping that can be
        expressed more declaratively. Leave deduplication and other refactors to their
        dedicated workflows. Ensure the new construct improves readability, keeps
        allocations in check, and passes existing tests. Document the before/after logic
        briefly in the commit message so reviewers can see the rationale.
