name: Codex 78 – Architectural Audit

on:
  schedule:
    - cron: "40 3 * * *" # daily at 03:40 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Architectural Audit"
      pr_body: |
        Seed PR asking Codex to audit repository architecture, document findings, and
        land a focused first-step refactor that keeps the codebase cohesive.
      prompt: >
        Perform a daily architectural audit of the repository to identify and correct structural inefficiencies while preserving public
        APIs and system behavior. Scan for redundant or fragmented top-level concepts, such as duplicated CLI entry points, overly deep
        directory hierarchies, or trivial single-function modules. Evaluate whether each directory or module represents a clear, cohesive
        concept and flag areas where merging or flattening would improve clarity and maintainability. Design and execute one focused,
        high-impact refactor per audit that simplifies the repository structure and moves it closer to the target architectural layout,
        keeping all APIs stable and tests passing. Summarize the findings, document the rationale for the refactor, and include
        before-and-after comparisons demonstrating the structural improvement. Start with a design rationale that summarizes current pain
        points and the intended target architecture. Explain a migration or fallback plan before carrying out sweeping file moves, keeping
        the changed file count manageable (under 15) and deferring additional moves to follow-up issues if necessary. Update imports,
        exports, documentation, and references so the project builds cleanly after the restructure.
