name: Codex 38 – Logic Deduplication
on:
  schedule:
    - cron: "0 */3 * * *" # every 3 hours
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    uses: ./.github/workflows/_codex-open-pr-and-ping.yml
    secrets: inherit
    with:
      pr_title: "Codex: Logic Deduplication"
      pr_body: "Seed PR for Codex to collapse repeated logic into a single path."
      prompt: >
        Hunt for duplicated conditionals, switch statements, or near-identical helper
        bodies that drift across the codebase. Select one small cluster and unify it by
        extracting a shared helper, reusing an existing one, or routing both code paths
        through the same implementation. When extracting something new, strongly prefer
        helpers that will see at least three call sites and hold five or more lines of
        executable logic (excluding comments and blank lines), unless you have a clear
        justification to diverge. Avoid expanding scope—focus on a single, well-understood
        duplication, keep naming and APIs stable, and add/regress tests as needed so the
        unified path stays safe. In your commit message, call out where the duplication
        lived and the helper/path that now covers it.
